name: comp47360_env2
channels:
  - conda-forge
  - defaults
dependencies:

  - python==3.9
  - pip
  - pip:
    - pycaret==3.0.4
    - django-cors-headers
  - lightgbm==3.3.5
  - asgiref
  - certifi
  - django
  - flit-core
  - nodejs
  - psycopg2
  - tk
  - djangorestframework==3.14.0
  - drf-spectacular>=0.15.1
  - requests
  - pandas
  - django-pandas
  - scikit-learn







